### PR TITLE
Symmetric improvements

### PR DESCRIPTION
**Pull request by ghost**
This implments the GCM mode of operation for several ciphers. It also has support for AESNOMAC (which users should steer clear of). It will require a change to trousseu for the function calls.

### CODE REVIEW

**Comment by ghost** [comment]
@oleiade - I changed this to use GCM as the default but left the ability to use the old AES in there as discussed in trousseau/#157. This requires more changes to trousseau, mainly editing the command line so that you can choose the algo - I will work on them as well.

Please let me know what you think of the API changes. The other route is to make a separate encrypter for each algo - but went this way instead.

**Comment by oleiade** [comment]
Hi @jd1123 

Thanks a lot for the hardwork on this. Even though I think it goes in the right direction, I think the changes it implies are a bit too brutal :-)

The main idea and goal with the `Encrypter` and `Decrypter` interfaces was to provide an as minimalist and simplistic API as possible. I made them with the idea of passing them around to functions agnostically of their type, algorithm, mode and so on. 

I do believe that a `SymmetricEncrypter` and `AsymmetricEncrypter` have their reasons to be, but as interfaces, definetly not as implementations, and not without each other. With this goes my intuition that it is necessary to keep the subpackages model -> interfaces.go + aes package + openpgp package + salsa20 package etc...
Plus, I can't think of a generic model enough for `AsymmetricEncrypter`, and unfortunately that is because of the Go language design itself: recipients of asymmetric encryption can be of very mixed types, and it would be a hell to make them fit inside a single interface type.

However I think you work on AES mode is to be kept, but integrated as part of the AES256Encrypter, using a cipher attribute or something that would define with a `switch` statement which aes cipher to use.

Plus, I ignored twofish and blowfish algorithms on purpose because I've read here and there that were kind of considered as deprecated and unsafe by the community when used by themselves. I was considering to add a salsa20 package instead: https://github.com/oleiade/serrure/issues/3

Let me know what you think :-)

**Comment by ghost** [comment]
@oleiade -

Noted and done - I will change this PR to reflect this (push the commit later tonight or tomorrow).

I will hold off on twofish and blowfish if you'd like (blowfish does not work with GCM as its blocksize is incompatible) - but frankly I use twofish myself locally with trousseau.

For Salsa20 - I will have to look into this more deeply as it it not a block cipher and doesn't fit the mold of AES or Twofish so easily. After some research I will consider doing another PR with its implementation. 

After I finish this PR, I'll change the trousseau PR as well.

**Comment by ghost** [comment]
closing this PR

**Pull request closed without merging**
